/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package learntrainevolve;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

    }
}
