version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "learn-train-evolve-service"
region = "us-east-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
s3_prefix = "learn-train-evolve-service"
parameter_overrides = "CognitoDomain=\"learn-train-evolve-service-ph\" S3Bucket=\"nss-s3-c02-capstone-learn-train-evolve-service-ph\" FrontendDeployment=\"remote\""
